# Generated by Django 3.2.6 on 2021-09-11 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'TO_DO'), (1, 'IN_PROGRESS'), (2, 'DONE')], default=0)),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'LOW_PRIORITY'), (1, 'MIDDLE_PRIORITY'), (2, 'HIGH_PRIOIRTY')], default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_finished', models.DateTimeField(null=True)),
                ('date_finished_planned', models.DateTimeField(default=main.models.return_date_time)),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('finished_tasks_num', models.IntegerField(default=0)),
                ('all_tasks_num', models.IntegerField(default=0)),
                ('sucess_coefficicent', models.FloatField(default=1)),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistic_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
