version: "3.9"
   
services:
  redis:
    image: redis:alpine
    env_file: .credentials/.devcontainer.env
    command: "redis-server --requirepass 111"
    ports:
      - '6379:6379'
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    env_file: .credentials/.devcontainer.env
    # environment:
    #   - RABBITMQ_DEFAULT_USER=guest
    #   - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5673:5672" 
  celery:
    restart: always
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    command: celery -A chocotodo worker -l info 
    volumes:
      - ../:/workspace:cached
    env_file: .credentials/.devcontainer.env
    depends_on:
      - db
      - redis
      - app
      - rabbitmq
  db:
    image: postgres
    env_file: .credentials/.devcontainer.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file: .credentials/.devcontainer.env
    volumes:
      - ../:/workspace:cached
    ports:
      - "8000:8000"
    depends_on:
      - db